version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:lts

jobs:
  install-dependencies:
    executor: main-executor
    parameters:
      app:
        type: string
    steps:
      - checkout
      - run: 
          command: npm ci
          working_directory: ./<< parameters.app >>
      - persist_to_workspace:
          root: ./
          paths:
            - << parameters.app >>/node_modules

  check-format:
    executor: main-executor
    parameters:
      app:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          command: npm run format:check
          working_directory: ./<< parameters.app >>
  
  lint:
    executor: main-executor
    parameters:
      app:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          command: npm run lint
          working_directory: ./<< parameters.app >>

  build:
    executor: main-executor
    parameters:
      app:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          command: npm run build        
          working_directory: ./<< parameters.app >>
      - persist_to_workspace:
          root: ./
          paths:
            - << parameters.app >>/dist

workflows:
  version: 2

  deploy:
    jobs:
      - install-dependencies:
          app: frontend
          name: frontend-install-dependencies
          filters:
            tags:
              only: /.*/
      - install-dependencies:
          app: backend
          name: backend-install-dependencies
          filters:
            tags:
              only: /.*/
      - check-format:
          app: frontend
          name: frontend-check-format
          requires:
            - frontend-install-dependencies
          filters:
            tags:
              only: /.*/
      - check-format:
          name: backend-check-format
          app: backend
          requires:
            - backend-install-dependencies
          filters:
            tags:
              only: /.*/
      - lint:
          app: frontend
          name: frontend-lint
          requires:
            - frontend-install-dependencies
          filters:
            tags:
              only: /.*/
      - build:
          name: frontend-build
          app: frontend
          requires:
            - frontend-install-dependencies
            - frontend-lint
            - frontend-check-format
          filters:
            tags:
              only: /.*/
      - build:
          name: backend-build
          app: backend
          requires:
            - backend-install-dependencies
            - backend-check-format
          filters:
            tags:
              only: /.*/